#!/bin/bash

# This is a simple wrapper for g++ that uses some recommended flags to promote
# debugging, compiler strictness, warnings as errors


if [ -z "$1" ]
then
 echo "Usage: `basename $0` target-file"
 exit 65
fi
if [[ "$1" != *.cpp ]]
then
 echo "Usage: `basename $0` target-file.cpp"
 exit 65
fi

g++ -std=c++20 -Werror -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -ggdb -pedantic-errors "$1" -o "${1/.cpp/.o}"
