name: 'C++ CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run:
        find . -name '*.cpp' -exec ./tools/g+++ {} \;
	find . -name '*.o'


